version: "3.9"
services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "tourismo"
      POSTGRES_USER: "tourismo"
      POSTGRES_PASSWORD: "tourismo"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres:
